name: Deploy to GitHub Pages (Branch Previews)

on:
  push:
    branches-ignore: [gh-pages]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Set base path
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "ASTRO_BASE=/ppegjs-demo/" >> "$GITHUB_ENV"
          else
            echo "ASTRO_BASE=/ppegjs-demo/preview/${{ github.ref_name }}/" >> "$GITHUB_ENV"
          fi
      - name: Install, build, and upload your site output
        uses: withastro/action@v5
      - name: Deploy to gh-pages (main)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref_name == 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
      - name: Deploy to gh-pages (preview)
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref_name != 'main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ format('preview/{0}', github.ref_name) }}
          keep_files: true
